### ISSUE TITLE
Lack of authentication when escalating issues

### ISSUE THREAD

**Issue by jobertabma** [urbandictionary/hackerone-pivotaltracker#1]
First of all, thanks a ton for open sourcing this - we're cheering for you here at HackerOne! One thing that caught my eye when reading the readme and checking out the code, is that there's no mention of any form of authentication when escalating an issue. There's a few ways we could address this: either suggest adding a secret to the Heroku app name (fast solution but not really sustainable) or adding a parameter to the `/create` endpoint (preferred). The secret could be a value in `profiles.clj` the user has to provide and be checked with a secure compare in the request.

Let me know your thoughts. Happy to write up either of the proposed solutions in a pull request!

**Comment by apeckham** [comment]
You're right! We chose a random Heroku app name, but that could be discovered...

It makes sense to require a "secret" param that must equal an env var. Feel free to send a PR if you like! Also if you add it to app.json, then people who use the Heroku button can specify the secret when the app is created.
